# Default values for first_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: kodekloud/simple-webapp
  pullPolicy: IfNotPresent
  tag: blue
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  name: my-service
  type: NodePort
  port: 8080
  nodePort: 30007
data:
  name: my-deployment
  labels:
    app: nginx
  port:
    number: 8080
    name: http
    protocol: TCP
  configmap:
    name: my-config-map
