apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.data.labels.app }}
  ports:
    - port: {{ .Values.data.port.number }}
      targetPort: {{ .Values.data.port.number }}
      nodePort: {{ .Values.service.nodePort}}
